src/Models/EventsListBlock.cs
using UmbracoGridConfigLoader.Attributes;
using UmbracoGridConfigLoader.Models;

namespace Graph.Components.EventsListBlock
{
	public class EventsListBlock : IGridConfigLoader
	{
		[GridLayoutProperty(Label = "Events List Block", AllowedEditors = new[] { "EventsListBlock" }, MaxItems = 1)]
		public IGridLayout Layout { get; set; }
	}
}

src/Models/EventsListBlockModel.cs
using System.Collections.Generic;

namespace Graph.Components.EventsListBlock
{
	public class EventsListBlockModel
	{
		public IEnumerable<EventsListItem> Events { get; set; }
		public PageNavigationModel PageNavigationModel { get; set; }
	}
}

src/Models/EventsListItem.cs
using System;

namespace Graph.Components.EventsListBlock
{
	public class EventsListItem
	{
		public string Title { get; set; }
		public string Description { get; set; }
		public DateTime StartDate { get; set; }
		public DateTime? EndDate { get; set; }
		public string Image { get; set; }
		public string Location { get; set; }
		public string Url { get; set; }
	}
}

src/Models/PageItem.cs
namespace Graph.Components.EventsListBlock
{
	public class PageItem
	{
		public int PageId { get; set; }
		public string Page { get; set; }
	}
}

src/Models/PageNavigationModel.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace Graph.Components.EventsListBlock
{
	public class PageNavigationModel
	{
		public int CurrentPage { get; }
		public int ItemsAmount { get; }
		public int PageSize { get; }
		public bool HasNextPage { get; }
		public bool HasPrevPage { get; }
		public IEnumerable<PageItem> Pages { get; }

		public PageNavigationModel(int currentPage, int itemsAmount, int pageSize)
		{
			var pageCount = (int)Math.Ceiling((decimal)itemsAmount / EventsListBlockConfig.PageSize);

			CurrentPage = currentPage;
			ItemsAmount = itemsAmount;
			PageSize = pageSize;
			Pages = GetPageRange(currentPage, pageCount);
			HasNextPage = false;
			HasPrevPage = false;
			if (currentPage < Pages.Count())
			{
				HasNextPage = true;
			}
			if (currentPage > 1)
			{
				HasPrevPage = true;
			}
		}

		private IEnumerable<PageItem> GetPageRange(int currentPage, int pageCount)
		{
			var pageRange = new List<PageItem>();
			if (pageCount <= 8)
			{
				for (var i = 1; i <= pageCount; i++)
				{
					pageRange.Add(new PageItem { Page = i.ToString(), PageId = i });
				}
				return pageRange;
			}

			if (currentPage <= 5)
			{

				for (var i = 1; i <= (currentPage < 5 ? 5 : currentPage + 1); i++)
				{
					pageRange.Add(new PageItem { Page = i.ToString(), PageId = i });
				}

				pageRange.Add(new PageItem { Page = "…" });
				pageRange.Add(new PageItem
				{
					Page = pageCount.ToString(),
					PageId = pageCount
				});

			}
			else if (pageCount - currentPage < 6)
			{
				pageRange.Add(new PageItem { Page = "1", PageId = 1 });
				pageRange.Add(new PageItem { Page = "…" });
				for (var i = currentPage == pageCount - 5 ? currentPage - 1 : pageCount - 5; i <= pageCount; i++)
				{
					pageRange.Add(new PageItem
					{
						Page = i.ToString(),
						PageId = i
					});
				}
			}
			else
			{
				pageRange.Add(new PageItem { Page = "1", PageId = 1 });
				pageRange.Add(new PageItem { Page = "…" });
				for (var i = currentPage - 2; i <= currentPage + 2; i++)
				{
					pageRange.Add(new PageItem
					{
						Page = i.ToString(),
						PageId = i
					});
				}
				pageRange.Add(new PageItem { Page = "…" });
				pageRange.Add(new PageItem
				{
					Page = pageCount.ToString(),
					PageId = pageCount
				});
			}

			return pageRange;
		}
	}
}

src/Controllers/EventsListBlockApiController.cs
using Umbraco.Web.Editors;
using Umbraco.Web.Mvc;

namespace Graph.Components.EventsListBlock
{
	[PluginController("EventsListBlock")]
	public class EventsListBlockApiController : UmbracoAuthorizedJsonController
	{
		public EditorConfig GetEditorConfig()
		{
			return new EditorConfig
			{
				EventsListAlias = EventsListBlockConfig.EventsListPageAlias
			};
		}
	}

	public class EditorConfig
	{
		public string EventsListAlias { get; set; }
	}
}

src/Controllers/EventsListBlockSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Umbraco.Core.Models;
using Umbraco.Web;
using Umbraco.Web.Mvc;

namespace Graph.Components.EventsListBlock
{
	public class EventsListBlockSurfaceController : SurfaceController
	{
		public ActionResult EventsList(GridControlEventsListDataSourceItem[] dataSources, int page = 1)
		{
			var allEvents = new List<EventsListItem>();
			var totalEventsCount = 0;
			if (dataSources != null && dataSources.Any())
			{
				foreach (var dataSourceItem in dataSources)
				{
					var dataSourceContent = new UmbracoHelper(UmbracoContext.Current).TypedContent(dataSourceItem.Id);

					allEvents.AddRange(dataSourceContent.Descendants(EventsListBlockConfig.EventPageAlias)
						.Where(x => x.IsVisible())
						.Select(x => new EventsListItem
						{
							Title = x.GetPropertyValue<string>(EventsListBlockConfig.Title),
							Description = x.GetPropertyValue<string>(EventsListBlockConfig.Summary),
							Url = x.Url,
							StartDate = x.GetPropertyValue<DateTime>(EventsListBlockConfig.StartDate),
							EndDate = x.GetPropertyValue<DateTime>(EventsListBlockConfig.EndDate),
							Image = x.GetPropertyValue<IPublishedContent>(EventsListBlockConfig.Image)?.Url,
							Location = x.GetPropertyValue<string>(EventsListBlockConfig.Location)
						}));
				}

				totalEventsCount = allEvents.Count;
			}

			var events = allEvents.OrderByDescending(x => x.StartDate)
				.Skip((page - 1) * EventsListBlockConfig.PageSize)
				.Take(EventsListBlockConfig.PageSize);

			return View("/App_Plugins/EventsListBlock/Views/EventsList.cshtml", new EventsListBlockModel
			{
				Events = events,
				PageNavigationModel = new PageNavigationModel(page, totalEventsCount, EventsListBlockConfig.PageSize)
			});
		}
	}
}

src/Views/EventsList.cshtml
@using System;
@using System.Web.Mvc.Html
@inherits Umbraco.Web.Mvc.UmbracoViewPage<Graph.Components.EventsListBlock.EventsListBlockModel>

<div class="event-list">
	<div class="event-list__container">
		<div class="event-list__items">
		@foreach (var item in Model.Events)
		{
			<div class="event">
				<div class="event__image-container">
					<div class="event__media">
						@if (item.Image != null) {
							<img class="event__img" src="@item.Image">
						}
					</div>
				</div>
				<div class="event__content">
					<h3 class="event__title">
						<a class="event__link" href="@item.Url">@item.Title</a>
					</h3>
					<div class="event__description">@item.Description</div>
					<address class="event__location">@item.Location</address>
					<time class="event__date">
						@item.StartDate.ToString("dd MMM yyyy")
						@if (item.EndDate.HasValue)
						{
							if (item.StartDate.Date == item.EndDate.Value.Date)
							{
  								<span>, @item.StartDate.ToString("hh:mm tt") - @item.EndDate.Value.ToString("hh:mm tt")</span>
							}
							else
							{
								<span> - @item.EndDate.Value.ToString("dd MMM yyyy ")</span>
							}
						}
						else
						{
							<span> @item.StartDate.ToString("hh:mm tt")</span>
						}
					</time>
				</div>
			</div>
		}
		</div>
		<div class="event-list__navigation">
			@Html.Partial("/App_Plugins/EventsListBlock/Views/EventsListNavigation.cshtml", Model.PageNavigationModel)
		</div>
	</div>
</div>

src/Views/EventsListBlockRender.cshtml
@using System.Web.Mvc.Html
@using Skybrud.Umbraco.GridData.Rendering
@inherits Umbraco.Web.Mvc.UmbracoViewPage<GridControlWrapper<Graph.Components.EventsListBlock.GridControlEventsListBlockValue>>

@Html.Action("EventsList", "EventsListBlockSurface", new { dataSources = Model.Value.EventsListDataSources })

src/Views/EventsListNavigation.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<Graph.Components.EventsListBlock.PageNavigationModel>

@{
	var pageCount = Model.ItemsAmount;
	var itemsCount = pageCount < Model.PageSize ? pageCount : Model.PageSize;
}
@functions
{

	string GetUrl(int page)
	{
		return $"?page={page}";
	}

}

@if (Model.PageSize < pageCount)
{
	<div class="pagination">
		@if (Model.HasPrevPage)
		{
			<a href="@GetUrl(Model.CurrentPage - 1)" class="pagination__item"><</a>
		}

		@foreach (var p in Model.Pages)
		{
			if (p.PageId == Model.CurrentPage)
			{
				<span class="pagination__item pagination__item_active">@p.PageId</span>
			}
			else
			{
				if (p.PageId == 0)
				{
					<span class="pagination__dots">...</span>
				}
				else
				{
					<a class="pagination__item" href="@GetUrl(p.PageId)">@p.PageId</a>
				}
			}
		}

		@if (Model.HasNextPage)
		{
			<a href="@GetUrl(Model.CurrentPage + 1)" class="pagination__item pagination__item_next">></a>
		}
	</div>
}

src/Views/GridRow.cshtml
@using Skybrud.Umbraco.GridData
@using Skybrud.Umbraco.GridData.Extensions
@inherits Umbraco.Web.Mvc.UmbracoViewPage<GridRow>

@foreach (var area in Model.Areas)
{
	foreach (var control in area.Controls)
	{
		@Html.RenderGridControl(control, control.Editor.Render)
	}
}